# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc0eefcf6c5633a21d049a6e9935b10054a838841e161d975872e6929fc06a02fb0e5cdbbc4b69d06e99a2c895ae885df1c62f40557dd2a0a94c6d14a08a41e

test:
  secret_key_base: e46a37a7b45c38e62004a2f8ec85f01fb16470ef8b974eb901033aef3f57cab628d183356082f95532490be1692d2654ac176f49dc40325a288aee3bd3b88ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
